### ISSUE TITLE
Add Accessibility Information to Web Site

### ISSUE THREAD

**Issue by nicknisi** [NebraskaJS/2018.nejsconf.com#4]
Examples of information you can include: 
- Is the venue accessible to wheelchairs, including the specific room where the conference is being held? Are there accessible restrooms? Accessible parking? (You could mention this on the front page where you describe the venue, and include a link to the venue's accessibility page.) 
- Are the networking event and after-party accessible, if they are at a different location? 
- Are assistive listening devices available at the conference? (They are mentioned on the venue's accessibility page, so I assume they are available to you, but check) 
- Are you able to provide food options to people with food allergies? You have a question about this on the registration form, but it's good to specifically say you are able to accommodate food allergies. Also, does this include any food at the networking/after-party, or just the conference itself? 
- Perhaps also mention that attendees with disabilities can find a conference organizer/volunteer if they have any issues or need assistance during the conference.

**Comment by zachleat** [comment]
Fixed by @mattdsteele #6
